# Generated by Django 5.1.3 on 2024-11-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('department_phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginCredentials',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('USN', models.CharField(blank=True, max_length=20, null=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('administrator', 'Administrator')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.department')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField()),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Server.department')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField()),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.department')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='Server.message')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='Server.message')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], max_length=10)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.branch')),
                ('department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Server.department')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDetail',
            fields=[
                ('Tid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], max_length=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('fee_type', models.CharField(max_length=50)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.student')),
            ],
        ),
    ]
